### ISSUE TITLE
AmazonDynamoDBException: 1 validation error detected

### ISSUE THREAD

**Issue by szwed** [shikhar/kafka-connect-dynamodb#3]
The following configuration:

```
{
  "connector.class": "dynamok.sink.DynamoDbSinkConnector",
  "name": "kafka-2-dynamodb",
  "ignore.record.value": "true",
  "ignore.record.key": "true",
  "kafka.attributes": "kafka_topic,kafka_partition,kafka_offset",
  "region": "us-west-2",
  "topics": "postgres-company"
}
```

results in:

```
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: 1 validation error detected: Value '{postgres-company=[com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a1e, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a1f, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a20, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a19, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a1a, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a1b, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a1c, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a15, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a16, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195a17, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c0d, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c0e, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c0f, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c10, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c09, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c0a, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c0b, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c0c, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c05, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c06, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195c14, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195bad, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195bae, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195baf, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195bb0, com.amazonaws.dynamodb.v20120810.WriteRequest@ab195ba9]}' at 'requestItems' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 25, Member must have length greater than or equal to 1] (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 1755G6B303RMBUD7FOO0647HFNVV4KQNSO5AEMVJF66Q9ASUAAJG)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1386)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:939)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:714)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:465)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2078)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2048)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.batchWriteItem(AmazonDynamoDBClient.java:811)
    at dynamok.sink.DynamoDbSinkTask.put(DynamoDbSinkTask.java:103)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:381)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:227)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by shikhar** [comment]
Error appears to be because of sending more than 25 puts in that batch, I wasn't aware of that limit (documented here: http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html)

**Comment by szwed** [comment]
Works better now. Thanks!
