### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by szwed** [shikhar/kafka-connect-dynamodb#4]
The following configuration:

```
{
  "connector.class": "dynamok.source.DynamoDbSourceConnector",
  "name": "dynamodb-2-kafka",
  "tables.regex": "dev",
  "region": "us-west-2"
}
```

results in:

```
[2016-10-12 13:14:59,052] ERROR Error while starting connector dynamodb-2-kafka (org.apache.kafka.connect.runtime.WorkerConnector)
java.lang.NullPointerException
    at dynamok.source.DynamoDbSourceConnector.start(DynamoDbSourceConnector.java:100)
    at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:100)
    at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:125)
    at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:182)
    at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:178)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:789)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startWork(DistributedHerder.java:755)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.handleRebalanceCompleted(DistributedHerder.java:715)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:206)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:176)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by szwed** [comment]
After a small investigation it seems that NPE is thrown when the (optional?) variable tables.whitelist is not provided..

**Comment by szwed** [comment]
Still throwing NPE, even if most of the variables are set:

```
{
  "connector.class": "dynamok.source.DynamoDbSourceConnector",
  "name": "dynamodb-2-kafka",
  "tables.prefix": "test",
  "region": "us-west-2",
  "tables.whitelist": "test,bb",
  "tables.blacklist": "aa,cc",
  "topic.format": "$(table)"
}
```

log:

```
[2016-10-13 14:15:36,971] ERROR Error while starting connector dynamodb-2-kafka (org.apache.kafka.connect.runtime.WorkerConnector)
java.lang.NullPointerException
    at dynamok.source.DynamoDbSourceConnector.start(DynamoDbSourceConnector.java:98)
    at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:100)
    at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:125)
    at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:182)
    at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:178)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:789)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.processConnectorConfigUpdates(DistributedHerder.java:307)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:279)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:176)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by shikhar** [comment]
@szwed are streams enabled for this DynamoDB table? I think `tableDesc.getStreamSpecification()` is returning `null`: https://github.com/shikhar/kafka-connect-dynamodb/blob/c53ad463c828eaf6574b135d112553790d900403/src/main/java/dynamok/source/DynamoDbSourceConnector.java#L98

I'll add an explicit null-check

**Comment by szwed** [comment]
Yeahh, that was it. Now all is fine, thanks !
