### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List

### ISSUE THREAD

**Issue by szwed** [shikhar/kafka-connect-dynamodb#5]
When using the following config:

```
{
  "connector.class": "dynamok.source.DynamoDbSourceConnector",
  "name": "dynamodb-2-kafka",
  "tables.regex": "test",
  "tables.whitelist": "test",
  "region": "us-west-2"
}
```

it results with:

```
[2016-10-12 14:22:22,699] ERROR Error while starting connector dynamodb-2-kafka (org.apache.kafka.connect.runtime.WorkerConnector)
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
    at org.apache.kafka.common.config.AbstractConfig.getList(AbstractConfig.java:100)
    at dynamok.source.ConnectorConfig.<init>(ConnectorConfig.java:64)
    at dynamok.source.DynamoDbSourceConnector.start(DynamoDbSourceConnector.java:74)
    at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:100)
    at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:125)
    at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:182)
    at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:178)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:789)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.processConnectorConfigUpdates(DistributedHerder.java:307)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:279)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:176)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by szwed** [comment]
After a small investigation it seems that the exception is only thrown when I provide variable **tables.whitelist**. 

Tried:
- tables.whitelist=table
- tables.whitelist=table1,table2,table3
- tables.whitelist={table}
- tables.whitelist={"table"}

always with the same result..

**Comment by shikhar** [comment]
@szwed there was a bug, fixed with https://github.com/shikhar/kafka-connect-dynamodb/commit/bd74f0852ba4bf9275e878de91b340825514b293

I'll create a 0.1.1 release soon with that fix.
